$sponsors = array("REWE",
					"Kömmerling",
					"Bayer",
					"Evonik Industries",
					"Deutsche Postbank",
					"Indeed",
					"WWK",
					"Telekom",
					"Gazprom",
					"Emirates",
					"Heinz von Heiden",
					"bet at home",
					"Red Bull",
					"Schwarzwaldmilch",
					"Wiesenhof",
					"SAP",
					"Mercedes-Benz-Bank",
					"Volkswagen");